### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by unilama**
Core of notifications service with first integration Slack

Related Issue: #20

### CODE REVIEW

**Comment by RobinUS2** [comment]
Looks good. Could you maybe add a small thing to README so we know how to configure Slack hooks?

**Comment by unilama** [comment]
Documentation is added and template of config too

**Comment by RobinUS2** [comment]
I merged the other one, but now this one became unmergable..

**Comment by unilama** [comment]
Mergable again

**Pull request merged**
